runtime: custom
env: flex

liveness_check:
   path: '/api/tests'
   check_interval_sec: 120
   timeout_sec: 40
   failure_threshold: 5
   success_threshold: 5
   initial_delay_sec: 500

entrypoint: python app.py

readiness_check:
  path: '/api/tests'
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 600

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 6
  disk_size_gb: 10